# Generated by Django 2.0.7 on 2018-08-01 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180801_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='date',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='time',
        ),
    ]
